project:
  type: book
  output-dir: book1

book:
  title: "통알못을 위한 기초통계 1"
  author: "Sapientia a Dei"
  date: "2023. 3. 29."
  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
    - references.qmd
  page-navigation: true
  cover-image: cover.png

bibliography: references.bib

format:
  html:
    theme: spacelab
    css: style.css
editor: visual

